import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/shared/Navbar'
import Footer from '@/components/shared/Footer'
import { Container } from '@mui/material'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The Dragon News',
  description: 'Generated by The Dragon News',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Container sx={{ minHeight: '52.3vh' }} >
          {children}
        </Container>
        <Footer />
      </body>

    </html>
  )
}
